name: app_book
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  shared_preferences: ^2.0.0
  vocsy_epub_viewer: ^1.0.0
  path_provider: ^2.0.0
  permission_handler: ^8.0.0
  flutter_cache_manager: ^3.0.0

dev_dependencies:
  test: any
  mockito: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
